
heat_template_version: 2013-05-23

description: |
  Single Linux server running the latest stable version of
  [memcached](http://memcached.org/).

parameter_groups:

- label: Server Settings
  parameters:
  - image
  - flavor

- label: Memcached Settings
  parameters:
  - memcached_port
  - memory_percentage

- label: rax-dev-params
  parameters:
  - server_hostname
  - kitchen
  - chef_version

parameters:

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment.
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  server_hostname:
    label: Hostname
    description: Hostname for the server.
    type: string
    default: memcache

  memory_percentage:
    label: Allowed Memory Size
    description: Percentage of memory memcached is allowed to use
    type: number
    default: 60

  memcached_port:
    label: Memcached Port
    description: Port memcached will listen on
    type: number
    default: 11211

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/memcached

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 12.3.0

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  memcached_server:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

  memcached_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: memcached_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [memcached_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        rax_memcached:
          mem_percent: { get_param: memory_percentage }
        memcached:
          port: { get_param: memcached_port }
        run_list: ["recipe[apt]",
                   "recipe[firewall]",
                   "recipe[rax-memcached::firewall]",
                   "recipe[rax-memcached::default]"]

outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    description: Server IP
    value: { get_attr: [memcached_server, accessIPv4] }

  memcached_port:
    description: Memcached Port
    value: { get_param: memcached_port }
